### ISSUE TITLE
Issue running wharfee on OL6

### ISSUE THREAD

**Issue by craigbarrau** [j-bennet/wharfee#97]
Awesome idea! Just wish I could use it...
I'm having some issues running wharfee on OracleLinux6. Is this a supported operating system?

Steps to reproduce:
1. Install
`sudo yum install -y python python-pip`
`sudo pip install wharfee`

2. Run
`wharfee`

The error message is
`Traceback (most recent call last):
  File "/usr/bin/wharfee", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: fuzzyfinder>=1.0.0`

`$ uname -a`
`Linux localhost.localdomain 3.8.13-68.3.4.el6uek.x86_64 #2 SMP Tue Jul 14 15:03:36 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux`

`$ docker info`

`Containers: 21
Images: 419
Storage Driver: devicemapper
 Pool Name: docker-8:3-2622386-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 32.4 GB
 Data Space Total: 107.4 GB
 Data Space Available: 22.13 GB
 Metadata Space Used: 33.35 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.114 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.89-RHEL6 (2014-09-01)
Execution Driver: native-0.2
Kernel Version: 3.8.13-68.3.4.el6uek.x86_64
Operating System: <unknown>
CPUs: 1
Total Memory: 11.49 GiB
Name: localhost.localdomain
ID: 5TLA:2UHL:QXA5:5NZN:WVIZ:NASL:EI77:OLYD:QODZ:K4NI:HTXS:267B`

**Comment by j-bennet** [comment]
I'll look into this. Thanks for reporting!

**Comment by amjith** [comment]
Can you try installing directly from the git repo? 

```
sudo pip install https://github.com/j-bennet/wharfee/archive/master.zip
```

Some of the older pip is having an issue with python packages. This should hopefully help.

**Comment by craigbarrau** [comment]
@amjith same issue. This is what I ran:
`sudo pip uninstall -y wharfee`
`sudo pip install https://github.com/j-bennet/wharfee/archive/master.zip`

**Comment by j-bennet** [comment]
I tried installing this way in a container based on Oracle Linux 6, and it seems to work for me:

```
yum update
yum install -y python python-dev python-setuptools git
easy_install http://github.com/j-bennet/wharfee/tarball/master
```

Please give it a try.

**Comment by wallnerryan** [comment]
+1 same issue on Mac OSX, using ```easy_install http://github.com/j-bennet/wharfee/tarball/master``` fixed this issue for me

**Comment by craigbarrau** [comment]
@j-bennet 
There is no python-dev package in Centos/RH/OL 6 repository. I changed it to python-devel as it appears to be the equivalent as per http://stackoverflow.com/questions/23541205/cant-install-python-dev-on-centos-6-5

The new error I am getting is 
`
Traceback (most recent call last):
  File "/usr/bin/wharfee", line 9, in <module>
    load_entry_point('wharfee==0.6.6', 'console_scripts', 'wharfee')()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 299, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2229, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1948, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.6/site-packages/wharfee-0.6.6-py2.6.egg/wharfee/main.py", line 29, in <module>
    from .formatter import format_data
  File "/usr/lib/python2.6/site-packages/wharfee-0.6.6-py2.6.egg/wharfee/formatter.py", line 416
    filtered = {k: v for k, v in item.items()
                       ^
SyntaxError: invalid syntax
`

I also tried uninstalling and running the following, but same issue
`
pip install git+https://github.com/j-bennet/wharfee.git
`

When I get a chance I'll try with a fresh VM in case there is any junk getting persisted. What OS would you recommend for Wharfee? I can be quite flexible as developing on multiple OSes is not a challenge for me with Vagrant. I would prefer to not go native Mac OSX if possible.

**Comment by j-bennet** [comment]
@craigbarrau: please try the installing the latest (0.6.7) with easy_install as above. The last error you have should be fixed in there.

I try to have wharfee work on as many OS-es as possible, but it've mostly been testing on Mac and Ubuntu.

**Comment by j-bennet** [comment]
Notes to self.

I've been digging into this issue further. It seems like pip and / or setuptools have problems installing certain packages under 2.6, even though these packages are 2.6-compliant. I'm not exactly sure what is different about those packages. But the following works:

```
easy_install pip
easy_install fuzzyfinder argparse requests click prompt_toolkit
pip install wharfee
```

So wharfee itself can be pip-installed in 2.6 just fine. But some of the packages it depends on - can't.

List of those packages:

```
argparse
click
fuzzyfinder
prompt_toolkit
requests
```

TODO: is there something in common in setup.py of those packages that won't let them be installed with 2.6's pip?
